In [1]:
import matplotlib.pyplot as plt
import cv2
import numpy as np
import os
from pycocotools.coco import COCO

In [2]:
def get_file_names(folder_path):
    """Returns a list of file names in the given folder path"""
    file_names = []
    for filename in os.listdir(folder_path):
        if os.path.isfile(os.path.join(folder_path, filename)):
            file_names.append(filename)
    return file_names

In [3]:
base_folder = 'C:/Users/chuck/OneDrive/Desktop/Honors/PV-Module-Finder/train/'
raw_img_dir = f'{base_folder}Raws/'
mask_img_dir = f'{base_folder}Masks/'

img_paths = get_file_names(raw_img_dir)


In [4]:
def rotate_augment(img_path, raw_img_dir, mask_img_dir):
    # Load the image using OpenCV
    image = cv2.imread(f"{raw_img_dir}{img_path}")
    mask = cv2.imread(f"{mask_img_dir}{img_path}")

    for i in range(3):
        # Rotate the image by 90 degrees clockwise
        image = cv2.rotate(image, cv2.ROTATE_90_CLOCKWISE)
        cv2.imwrite(f"{raw_img_dir}{i}_{img_path}", image)
        mask = cv2.rotate(mask, cv2.ROTATE_90_CLOCKWISE)
        cv2.imwrite(f"{mask_img_dir}{i}_{img_path}", mask)

In [5]:
for path in img_paths:
    rotate_augment(path, raw_img_dir, mask_img_dir)

In [9]:
# for example
image = cv2.imread("example_raw.jpg")
print(image)
mask = cv2.imread("example_mask.jpg")

for i in range(3):
        # Rotate the image by 90 degrees clockwise
        image = cv2.rotate(image, cv2.ROTATE_90_CLOCKWISE)
        cv2.imwrite(f"example_raw{i}.jpg", image)
        mask = cv2.rotate(mask, cv2.ROTATE_90_CLOCKWISE)
        cv2.imwrite(f"example_mask{i}.jpg", mask)

[[[174 174 174]
  [178 178 178]
  [180 180 180]
  ...
  [ 49  49  49]
  [ 42  42  42]
  [ 17  17  17]]

 [[177 177 177]
  [181 181 181]
  [182 182 182]
  ...
  [ 40  40  40]
  [ 44  44  44]
  [ 34  34  34]]

 [[177 177 177]
  [181 181 181]
  [182 182 182]
  ...
  [ 34  34  34]
  [ 32  32  32]
  [ 28  28  28]]

 ...

 [[186 186 186]
  [179 179 179]
  [174 174 174]
  ...
  [ 14  14  14]
  [ 18  18  18]
  [ 39  39  39]]

 [[186 186 186]
  [178 178 178]
  [172 172 172]
  ...
  [ 13  13  13]
  [ 23  23  23]
  [ 26  26  26]]

 [[177 177 177]
  [170 170 170]
  [167 167 167]
  ...
  [ 13  13  13]
  [ 26  26  26]
  [ 11  11  11]]]
